# This is a basic example of an Azure Static Web Apps workflow
# For more options, see the Azure Static Web Apps documentation:
# https://docs.microsoft.com/en-us/azure/static-web-apps/

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  APP_LOCATION: "/"
  API_LOCATION: "/api"
  APP_ARTIFACT_LOCATION: "/"

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd app
        npm install
    - name: Build
      run: |
        cd app
        npm run build --if-present
    - name: "Deploy to Azure Static Web Apps"
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        ###### Repository/
